const PERMISSION_CATEGORIES = {
  "Đơn hàng": ["viewSaleOrder", "manageSaleOrder"],
  "Yêu cầu mua": ["viewPurchaseRequest", "managePurchaseRequest"],
  "Duyệt yêu cầu mua": ["acceptPurchaseRequest"],
  "Đơn mua": ["viewPurchaseOrder", "managePurchaseOrder"],
  "Phiếu nhập kho": ["viewReceiptNote", "manageReceiptNote"],
  "Phiếu xuất kho": ["viewIssueNote", "manageIssueNote"],
  "Đơn vị": ["viewUnit", "manageUnit"],
  "Báo cáo": ["viewReport"],
  "Sản phẩm": ["viewProduct", "manageProduct"],
  "Dòng sản phẩm": ["viewProductType", "manageProductType"],
  "Đối tác": ["viewPartner", "managePartner"],
  "Kho": ["viewWarehouse", "manageWarehouse"],
  "Vật tư": ["viewMaterial", "manageMaterial"],
  "Danh mục vật tư": ["viewMaterialType", "manageMaterialType"],
};

const PERMISSION_LABELS = {
  viewSaleOrder: "Xem",
  manageSaleOrder: "Quản lý",
  viewPurchaseRequest: "Xem",
  managePurchaseRequest: "Quản lý",
  acceptPurchaseRequest: "Duyệt",
  viewPurchaseOrder: "Xem",
  managePurchaseOrder: "Quản lý",
  viewReceiptNote: "Xem",
  manageReceiptNote: "Quản lý",
  viewIssueNote: "Xem",
  manageIssueNote: "Quản lý",
  viewUnit: "Xem",
  manageUnit: "Quản lý",
  viewReport: "Xem",
  viewProduct: "Xem",
  manageProduct: "Quản lý",
  viewProductType: "Xem",
  manageProductType: "Quản lý",
  viewPartner: "Xem",
  managePartner: "Quản lý",
  viewWarehouse: "Xem",
  manageWarehouse: "Quản lý",
  viewMaterial: "Xem",
  manageMaterial: "Quản lý",
  viewMaterialType: "Xem",
  manageMaterialType: "Quản lý",
};

export { PERMISSION_CATEGORIES, PERMISSION_LABELS };